# Generated by Django 5.2.1 on 2025-10-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.CharField(default='', max_length=150),
        ),
    ]
