# Generated by Django 5.2.1 on 2025-10-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
    ]
